<?php
/**
 * @file
 * Rights Statements Badges
 */

/**
 * Implements hook_menu().
 */
function islandora_questionpoint_qwidget_menu() {
  return array(
    'admin/islandora/tools/questionpoint' => array(
      'title' => 'Questionpoint Qwidget',
      'description' => 'Configure Questionpoint Qwidget settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_questionpoint_qwidget_admin_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_questionpoint_qwidget_block_info() {
  return array(
    'islandora_questionpoint_qwidget' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/search*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Questionpoint Qwidget'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_questionpoint_qwidget_block_view($delta = '') {
  module_load_include('inc', 'islandora_questionpoint_qwidget', 'includes/utilities');
  $to_render = array();
  $qwidget_code = islandora_questionpoint_qwidget_get_html();
  $to_render['content'] = $qwidget_code;
  return $to_render;
}
